[project]
name = "budget-utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "polars>=1.36.1",
    "pydantic>=2.12.5",
    "ynab>=1.9.0",
]

[project.scripts]
budget-utils = "budget_utils.cli:main"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "hypothesis>=6.148.9",
    "pytest>=8.4.2",
]

[tool.pytest.ini_options]
addopts = ["--doctest-modules"]
testpaths = ["tests", "src"]
